name: Run job-tracker - source 7 - LinkedIn (Data science)

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 2 */1 *' # monthly on day 2 at 10:00

jobs:
  run-container:
    runs-on: self-hosted

    steps:
      - name: Check if job-tracker image exists
        id: check-image
        run: |
          if docker image inspect job-tracker:latest &>/dev/null; then
            echo "image_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Image job-tracker:latest exists"
          else
            echo "image_exists=false" >> $GITHUB_OUTPUT
            echo "❌ Image job-tracker:latest does not exist"
          fi

      - name: Run container for source 7 - LinkedIn (Data science)
        if: steps.check-image.outputs.image_exists == 'true'
        env:
          NOTION_API: ${{ secrets.NOTION_API }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          FREE_MOBILE_USER_ID: ${{ secrets.FREE_MOBILE_USER_ID }}
          FREE_MOBILE_API_KEY: ${{ secrets.FREE_MOBILE_API_KEY }}
        run: |
          docker run -e NOTION_API=$NOTION_API \
                     -e DATABASE_ID=$DATABASE_ID \
                     -e FREE_MOBILE_USER_ID=$FREE_MOBILE_USER_ID \
                     -e FREE_MOBILE_API_KEY=$FREE_MOBILE_API_KEY \
                     --rm \
                     job-tracker:latest 6, 7
